services:
  db:
    build: 
      context: ./election-db
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=develop
      - MYSQL_DATABASE=election
    ports:
      - 3306:3306
  cache:
    image: redis:7.0
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
  app:
    image: node:12-alpine
    ports: 3000:3000
    command: sh -c "npm i && npm run dev"
    working_dir: /app
    volumes: ./election-app:/app
    depends_on:
      - db
      - cache
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379

volumes:
  db:
    driver: local
  cache:
    driver: local
